### ISSUE TITLE
Mrtvi linki

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#1]
Pod »obrazci, vloge, potrdila:«, »Zaključevanje študija« in »izmenjava« so številni mrtvi linki »povezave do podstrani«

[https://www.fgg.uni-lj.si/organizacijske-enote/referat-za-studijske-zadeve/](url)

**Comment by matevzdolenc** [comment]
To bomo uredili z referatom.

**Comment by gaspermrak** [comment]
ZAKLJUČITI
