### ISSUE TITLE
Informativni dan 2016 - I. stopnja

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#13]
Vsebina spletne strani ni bila prenesena (od podstrani pa je bila prenesena) [http://www3.fgg.uni-lj.si/vse-za-studij/vpis-20162017/informativni-dan-2016-i-stopnja/](url)

**Comment by matevzdolenc** [comment]
Mislim da ni potrebno - raje pripravimo stran za info dan 2017.

**Comment by gaspermrak** [comment]
Pripravila se bo nova stran za infromativne dneve v 2017. ZAKLJUČITI
