### ISSUE TITLE
Strani niso prenešene

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#14]
Iz stare spletne strani niso bile prenesene strani
1. [http://www3.fgg.uni-lj.si/vse-za-studij/pravilniki-obrazci-navodila/stari-dodiplomski-studiji/](url)
2. [http://www3.fgg.uni-lj.si/vse-za-studij/pravilniki-obrazci-navodila/stari-podiplomski-studiji/](url)
3. [http://www3.fgg.uni-lj.si/vse-za-studij/pravilniki-obrazci-navodila/arhiv/](url)

**Comment by matevzdolenc** [comment]
ad 1. ... študij je ukinjen . preveriti pri mojci
ad 2 ... študij je ukinjen . preveriti pri mojci 
ad 3 ... preveriti pri mojci

**Comment by gaspermrak** [comment]
OK vsi stari programi so sedaj v arhivu
