### ISSUE TITLE
Mednarodno sodelovanje

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#16]
Spletna stran [https://www.fgg.uni-lj.si/mednarodno-sodelovanje/](url) je prazna in ni prenesena od [http://www3.fgg.uni-lj.si/vse-za-studij/mednarodno-sodelovanje/](url)

**Comment by matevzdolenc** [comment]
To so sedaj mednarodne izmenjave.

**Comment by rklinc** [comment]
Se pripravljajo tudi institucije. Sem jih že uvozil.

**Comment by gaspermrak** [comment]
Potrebno je pregledati vse instutitucije, nekje manjkajo povezave na spletne strani, nekje ni pravi naslov za sedež fakultete ...
