### ISSUE TITLE
UL FGG se predstavi (video)

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#22]
[http://www3.fgg.uni-lj.si/vse-za-studij/ul-fgg-se-predstavi-video/](url) ni prenesena

**Comment by matevzdolenc** [comment]
Na obstoječi strani se zaženeta oba videa hkrati :-)

**Comment by gaspermrak** [comment]
sedaj je pomocijski film viden na klik ob študij
