### ISSUE TITLE
KPP

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#29]
Vsebina spletne strani [http://www3.fgg.uni-lj.si/oddelki-in-katedre/oddelek-za-geodezijo/kpp-katedra-za-prostorsko-planiranje/strokovno-delo/](url) ni prenesena na KPP -> »strokovno delo« [https://www.fgg.uni-lj.si/organizacijske-enote/katedra-za-prostorsko-planiranje/](url)

**Comment by matevzdolenc** [comment]
podatki so stari

**Comment by gaspermrak** [comment]
strokovno delel se disable-al dokler ne bo novih podatkov
