### ISSUE TITLE
Urnik ni viden na telefonu

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#36]
Urnik ni viden na telefonu

**Comment by matevzdolenc** [comment]
Robi: JE viden, samo v desno moraš it. Drugače ne gre. Sem ga pa zmanjšal, mogoče bo malo boljše.

**Comment by rklinc** [comment]
Tega se ne da spremeniti. To tako pač je. Sem dodatno še zmanjšal fonte in paddinge, morda se vidi malo več, čudežev pa ne morem narediti.
