### ISSUE TITLE
firefox / chrome problem

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#5]
Ko sledim povezavi »pogoji za vpis« na strani [https://www.fgg.uni-lj.si/studijski-programi-3-stopnje/grajeno-okolje/](url) V FireFox-u ne morem odpreti nobenega zavihka [kot so »Merila in kriteriji v primeru omejitve vpisa«,…](v chrome deluje). Če grem direktno na »pogoji za vpis« [https://www.fgg.uni-lj.si/pogoji-za-vpis-v-studijske-programe-na-ul-fgg](url) in poskusim odpreti zavihke deluje brezhibno.

[https://www.fgg.uni-lj.si/pogoji-za-vpis-v-studijske-programe-na-ul-fgg/#GRAJENO_DR](url)

**Comment by matevzdolenc** [comment]
Tole bo robi dobil.

**Comment by rklinc** [comment]
Tole je Robi že popravil.
