### ISSUE TITLE
Slika študenta

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#6]
Na dnu strani manjka »študij« »slika študenta« in »izjava študenta«. Je zgolj rdeč štirikotnik s »študij in študent« napisano v belem.

[https://www.fgg.uni-lj.si/studijski-programi-3-stopnje/varstvo-okolja/](url)

**Comment by matevzdolenc** [comment]
Gašper bo dobil tole, pravi ... se izvaja, čakam sliko od simona

**Comment by gaspermrak** [comment]
poslal mail še enkrat

**Comment by gaspermrak** [comment]
ZAKLJUČENO
