### ISSUE TITLE
Linki ne peljejo nikamor (navodila za vpis)

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#8]
Na dnu strani [https://www.fgg.uni-lj.si/navodila-za-vpis/](url) vse tri povezave ne vodijo nikamor:
- Predstavitvena brošura
- Učni načrti
- Predmetniki študijskih programov

**Comment by matevzdolenc** [comment]
Zanekrat samo disable-al, dogovoriti z mojco, če to objavimo tudi tu?

**Comment by gaspermrak** [comment]
Ni potrebno. Zakjljučiti ISSUE

**Comment by rklinc** [comment]
Matevž, daj povabi gašperja, da bo lahko zaprl issue.
