### ISSUE TITLE
Strani za 2 stopnjo študija: povezave ne delajo + slika

### ISSUE THREAD

**Issue by matevzdolenc** [matevzdolenc/UL-FGG-spletne-strani#9]
Na dnu strani [https://www.fgg.uni-lj.si/navodila-za-vpis-na-2-stopnjo-studija/](url) vse tri povezave ne vodijo nikamor:
- Predstavitvena brošura
- Učni načrti
- Predmetniki študijskih programov

Na isti strani spodaj levo je namesto slike sivi štirikotnik 300x300  dodatni je potrebno ali sliko, ali pa kako grafiko.

**Comment by matevzdolenc** [comment]
Gašper: Zanekrat samo disable-al, dogovoriti z mojco, če to objavimo tudi tu?

**Comment by gaspermrak** [comment]
urejeno ... ko bo aktualen vpis, se bodo strani dopolnile. ZAKLJUČENO
